version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Automatically merge minor and patch updates
    auto-merge: true
    # Group security updates together
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
    # Customize commit messages
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"
    # Review configuration
    reviewers:
      - "jimhill" # Replace with your GitHub username
    assignees:
      - "jimhill" # Replace with your GitHub username
    # Ignore specific packages if needed
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    # Vendor dependencies to update
    vendor: true
    # Target branch for pull requests
    target-branch: "main"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Allow up to 5 open pull requests for GitHub Actions
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"
      include: "scope"